// ⚠️ AUTO-GENERATED by /tmp/gen_dt_loader.mjs. Düzenleme: shard'lar üzerinde yap.
//
// Doctortakvimi havuzu (~160K hekim). Şehir bazlı, büyük şehirler (İstanbul, Ankara)
// için branş alt-shard'larla bölünmüş. Vercel build memory'sini patlatmamak için.

import type { DoctorSummary } from "./types";

import c0__izmir from "./dt-shards/izmir.json";
import c1__bursa from "./dt-shards/bursa.json";
import c2__antalya from "./dt-shards/antalya.json";
import c3__adana from "./dt-shards/adana.json";
import c4__gaziantep from "./dt-shards/gaziantep.json";
import c5__kocaeli from "./dt-shards/kocaeli.json";
import c6__konya from "./dt-shards/konya.json";
import c7__diyarbakir from "./dt-shards/diyarbakir.json";
import c8__denizli from "./dt-shards/denizli.json";
import c9__eskisehir from "./dt-shards/eskisehir.json";
import c10__aydin from "./dt-shards/aydin.json";
import c11__hatay from "./dt-shards/hatay.json";
import c12__balikesir from "./dt-shards/balikesir.json";
import c13__samsun from "./dt-shards/samsun.json";
import c14__mersin from "./dt-shards/mersin.json";
import c15__kayseri from "./dt-shards/kayseri.json";
import c16__erzurum from "./dt-shards/erzurum.json";
import c17__sakarya from "./dt-shards/sakarya.json";
import c18__mugla from "./dt-shards/mugla.json";
import c19__tekirdag from "./dt-shards/tekirdag.json";
import c20__manisa from "./dt-shards/manisa.json";
import c21__elazig from "./dt-shards/elazig.json";
import c22__isparta from "./dt-shards/isparta.json";
import c23__canakkale from "./dt-shards/canakkale.json";
import c24__edirne from "./dt-shards/edirne.json";
import c25__sanliurfa from "./dt-shards/sanliurfa.json";
import c26__trabzon from "./dt-shards/trabzon.json";
import c27__kahramanmaras from "./dt-shards/kahramanmaras.json";
import c28__malatya from "./dt-shards/malatya.json";
import c29__corum from "./dt-shards/corum.json";
import c30__van from "./dt-shards/van.json";
import c31__afyonkarahisar from "./dt-shards/afyonkarahisar.json";
import c32__adiyaman from "./dt-shards/adiyaman.json";
import c33__duzce from "./dt-shards/duzce.json";
import c34__ordu from "./dt-shards/ordu.json";
import c35__bolu from "./dt-shards/bolu.json";
import c36__batman from "./dt-shards/batman.json";
import c37__giresun from "./dt-shards/giresun.json";
import c38__zonguldak from "./dt-shards/zonguldak.json";
import c39__sivas from "./dt-shards/sivas.json";
import c40__aksaray from "./dt-shards/aksaray.json";
import c41__amasya from "./dt-shards/amasya.json";
import c42__tokat from "./dt-shards/tokat.json";
import c43__mardin from "./dt-shards/mardin.json";
import c44__agri from "./dt-shards/agri.json";
import c45__kutahya from "./dt-shards/kutahya.json";
import c46__afyon from "./dt-shards/afyon.json";
import c47__osmaniye from "./dt-shards/osmaniye.json";
import c48__usak from "./dt-shards/usak.json";
import c49__burdur from "./dt-shards/burdur.json";
import c50__erzincan from "./dt-shards/erzincan.json";
import c51__bitlis from "./dt-shards/bitlis.json";
import c52__kirklareli from "./dt-shards/kirklareli.json";
import c53__kastamonu from "./dt-shards/kastamonu.json";
import c54__yalova from "./dt-shards/yalova.json";
import c55__rize from "./dt-shards/rize.json";
import c56__bartin from "./dt-shards/bartin.json";
import c57__yozgat from "./dt-shards/yozgat.json";
import c58__bilecik from "./dt-shards/bilecik.json";
import c59__sirnak from "./dt-shards/sirnak.json";
import c60__bingol from "./dt-shards/bingol.json";
import c61__kars from "./dt-shards/kars.json";
import c62__nigde from "./dt-shards/nigde.json";
import c63__artvin from "./dt-shards/artvin.json";
import c64__cankiri from "./dt-shards/cankiri.json";
import c65__hakkari from "./dt-shards/hakkari.json";
import c66__nevsehir from "./dt-shards/nevsehir.json";
import c67__kirikkale from "./dt-shards/kirikkale.json";
import c68__karabuk from "./dt-shards/karabuk.json";
import c69__karaman from "./dt-shards/karaman.json";
import c70__mus from "./dt-shards/mus.json";
import c71__igdir from "./dt-shards/igdir.json";
import c72__kirsehir from "./dt-shards/kirsehir.json";
import c73__siirt from "./dt-shards/siirt.json";
import c74__sinop from "./dt-shards/sinop.json";
import c75__gumushane from "./dt-shards/gumushane.json";
import c76__ardahan from "./dt-shards/ardahan.json";
import c77__bayburt from "./dt-shards/bayburt.json";
import c78__tunceli from "./dt-shards/tunceli.json";
import c79__kilis from "./dt-shards/kilis.json";
import c80__istanbul__acil_tip from "./dt-shards/istanbul/acil-tip.json";
import c81__istanbul__aile_hekimligi from "./dt-shards/istanbul/aile-hekimligi.json";
import c82__istanbul__anesteziyoloji_ve_reanimasyon from "./dt-shards/istanbul/anesteziyoloji-ve-reanimasyon.json";
import c83__istanbul__beyin_ve_sinir_cerrahisi from "./dt-shards/istanbul/beyin-ve-sinir-cerrahisi.json";
import c84__istanbul__cocuk_cerrahisi from "./dt-shards/istanbul/cocuk-cerrahisi.json";
import c85__istanbul__cocuk_hastaliklari from "./dt-shards/istanbul/cocuk-hastaliklari.json";
import c86__istanbul__dermatoloji from "./dt-shards/istanbul/dermatoloji.json";
import c87__istanbul__dis_hekimligi from "./dt-shards/istanbul/dis-hekimligi.json";
import c88__istanbul__diyetisyen from "./dt-shards/istanbul/diyetisyen.json";
import c89__istanbul__endokrinoloji from "./dt-shards/istanbul/endokrinoloji.json";
import c90__istanbul__enfeksiyon_hastaliklari from "./dt-shards/istanbul/enfeksiyon-hastaliklari.json";
import c91__istanbul__estetik_cerrahi from "./dt-shards/istanbul/estetik-cerrahi.json";
import c92__istanbul__fizik_tedavi from "./dt-shards/istanbul/fizik-tedavi.json";
import c93__istanbul__gastroenteroloji from "./dt-shards/istanbul/gastroenteroloji.json";
import c94__istanbul__genel_cerrahi from "./dt-shards/istanbul/genel-cerrahi.json";
import c95__istanbul__gogus_cerrahisi from "./dt-shards/istanbul/gogus-cerrahisi.json";
import c96__istanbul__gogus_hastaliklari from "./dt-shards/istanbul/gogus-hastaliklari.json";
import c97__istanbul__goz_hastaliklari from "./dt-shards/istanbul/goz-hastaliklari.json";
import c98__istanbul__hematoloji from "./dt-shards/istanbul/hematoloji.json";
import c99__istanbul__ic_hastaliklari from "./dt-shards/istanbul/ic-hastaliklari.json";
import c100__istanbul__kadin_hastaliklari_ve_dogum from "./dt-shards/istanbul/kadin-hastaliklari-ve-dogum.json";
import c101__istanbul__kalp_ve_damar_cerrahisi from "./dt-shards/istanbul/kalp-ve-damar-cerrahisi.json";
import c102__istanbul__kardiyoloji from "./dt-shards/istanbul/kardiyoloji.json";
import c103__istanbul__kbb from "./dt-shards/istanbul/kbb.json";
import c104__istanbul__medikal_onkoloji from "./dt-shards/istanbul/medikal-onkoloji.json";
import c105__istanbul__nefroloji from "./dt-shards/istanbul/nefroloji.json";
import c106__istanbul__noroloji from "./dt-shards/istanbul/noroloji.json";
import c107__istanbul__ortodonti from "./dt-shards/istanbul/ortodonti.json";
import c108__istanbul__ortopedi_ve_travmatoloji from "./dt-shards/istanbul/ortopedi-ve-travmatoloji.json";
import c109__istanbul__psikiyatri from "./dt-shards/istanbul/psikiyatri.json";
import c110__istanbul__psikoloji from "./dt-shards/istanbul/psikoloji.json";
import c111__istanbul__radyasyon_onkolojisi from "./dt-shards/istanbul/radyasyon-onkolojisi.json";
import c112__istanbul__radyoloji from "./dt-shards/istanbul/radyoloji.json";
import c113__istanbul__romatoloji from "./dt-shards/istanbul/romatoloji.json";
import c114__istanbul__uroloji from "./dt-shards/istanbul/uroloji.json";
import c115__ankara__acil_tip from "./dt-shards/ankara/acil-tip.json";
import c116__ankara__aile_hekimligi from "./dt-shards/ankara/aile-hekimligi.json";
import c117__ankara__anesteziyoloji_ve_reanimasyon from "./dt-shards/ankara/anesteziyoloji-ve-reanimasyon.json";
import c118__ankara__beyin_ve_sinir_cerrahisi from "./dt-shards/ankara/beyin-ve-sinir-cerrahisi.json";
import c119__ankara__cocuk_cerrahisi from "./dt-shards/ankara/cocuk-cerrahisi.json";
import c120__ankara__cocuk_hastaliklari from "./dt-shards/ankara/cocuk-hastaliklari.json";
import c121__ankara__dermatoloji from "./dt-shards/ankara/dermatoloji.json";
import c122__ankara__dis_hekimligi from "./dt-shards/ankara/dis-hekimligi.json";
import c123__ankara__diyetisyen from "./dt-shards/ankara/diyetisyen.json";
import c124__ankara__endokrinoloji from "./dt-shards/ankara/endokrinoloji.json";
import c125__ankara__enfeksiyon_hastaliklari from "./dt-shards/ankara/enfeksiyon-hastaliklari.json";
import c126__ankara__estetik_cerrahi from "./dt-shards/ankara/estetik-cerrahi.json";
import c127__ankara__fizik_tedavi from "./dt-shards/ankara/fizik-tedavi.json";
import c128__ankara__gastroenteroloji from "./dt-shards/ankara/gastroenteroloji.json";
import c129__ankara__genel_cerrahi from "./dt-shards/ankara/genel-cerrahi.json";
import c130__ankara__gogus_cerrahisi from "./dt-shards/ankara/gogus-cerrahisi.json";
import c131__ankara__gogus_hastaliklari from "./dt-shards/ankara/gogus-hastaliklari.json";
import c132__ankara__goz_hastaliklari from "./dt-shards/ankara/goz-hastaliklari.json";
import c133__ankara__hematoloji from "./dt-shards/ankara/hematoloji.json";
import c134__ankara__ic_hastaliklari from "./dt-shards/ankara/ic-hastaliklari.json";
import c135__ankara__kadin_hastaliklari_ve_dogum from "./dt-shards/ankara/kadin-hastaliklari-ve-dogum.json";
import c136__ankara__kalp_ve_damar_cerrahisi from "./dt-shards/ankara/kalp-ve-damar-cerrahisi.json";
import c137__ankara__kardiyoloji from "./dt-shards/ankara/kardiyoloji.json";
import c138__ankara__kbb from "./dt-shards/ankara/kbb.json";
import c139__ankara__medikal_onkoloji from "./dt-shards/ankara/medikal-onkoloji.json";
import c140__ankara__nefroloji from "./dt-shards/ankara/nefroloji.json";
import c141__ankara__noroloji from "./dt-shards/ankara/noroloji.json";
import c142__ankara__ortodonti from "./dt-shards/ankara/ortodonti.json";
import c143__ankara__ortopedi_ve_travmatoloji from "./dt-shards/ankara/ortopedi-ve-travmatoloji.json";
import c144__ankara__psikiyatri from "./dt-shards/ankara/psikiyatri.json";
import c145__ankara__psikoloji from "./dt-shards/ankara/psikoloji.json";
import c146__ankara__radyasyon_onkolojisi from "./dt-shards/ankara/radyasyon-onkolojisi.json";
import c147__ankara__radyoloji from "./dt-shards/ankara/radyoloji.json";
import c148__ankara__romatoloji from "./dt-shards/ankara/romatoloji.json";
import c149__ankara__uroloji from "./dt-shards/ankara/uroloji.json";

// Şehir → ya () => DoctorSummary[] (tek shard) ya Map<specialty, () => arr> (big city)
type CityLoader = (() => DoctorSummary[]) | Map<string, () => DoctorSummary[]>;

const CITY_REGISTRY = new Map<string, CityLoader>([
  ["izmir", () => c0__izmir as unknown as DoctorSummary[]],
  ["bursa", () => c1__bursa as unknown as DoctorSummary[]],
  ["antalya", () => c2__antalya as unknown as DoctorSummary[]],
  ["adana", () => c3__adana as unknown as DoctorSummary[]],
  ["gaziantep", () => c4__gaziantep as unknown as DoctorSummary[]],
  ["kocaeli", () => c5__kocaeli as unknown as DoctorSummary[]],
  ["konya", () => c6__konya as unknown as DoctorSummary[]],
  ["diyarbakir", () => c7__diyarbakir as unknown as DoctorSummary[]],
  ["denizli", () => c8__denizli as unknown as DoctorSummary[]],
  ["eskisehir", () => c9__eskisehir as unknown as DoctorSummary[]],
  ["aydin", () => c10__aydin as unknown as DoctorSummary[]],
  ["hatay", () => c11__hatay as unknown as DoctorSummary[]],
  ["balikesir", () => c12__balikesir as unknown as DoctorSummary[]],
  ["samsun", () => c13__samsun as unknown as DoctorSummary[]],
  ["mersin", () => c14__mersin as unknown as DoctorSummary[]],
  ["kayseri", () => c15__kayseri as unknown as DoctorSummary[]],
  ["erzurum", () => c16__erzurum as unknown as DoctorSummary[]],
  ["sakarya", () => c17__sakarya as unknown as DoctorSummary[]],
  ["mugla", () => c18__mugla as unknown as DoctorSummary[]],
  ["tekirdag", () => c19__tekirdag as unknown as DoctorSummary[]],
  ["manisa", () => c20__manisa as unknown as DoctorSummary[]],
  ["elazig", () => c21__elazig as unknown as DoctorSummary[]],
  ["isparta", () => c22__isparta as unknown as DoctorSummary[]],
  ["canakkale", () => c23__canakkale as unknown as DoctorSummary[]],
  ["edirne", () => c24__edirne as unknown as DoctorSummary[]],
  ["sanliurfa", () => c25__sanliurfa as unknown as DoctorSummary[]],
  ["trabzon", () => c26__trabzon as unknown as DoctorSummary[]],
  ["kahramanmaras", () => c27__kahramanmaras as unknown as DoctorSummary[]],
  ["malatya", () => c28__malatya as unknown as DoctorSummary[]],
  ["corum", () => c29__corum as unknown as DoctorSummary[]],
  ["van", () => c30__van as unknown as DoctorSummary[]],
  ["afyonkarahisar", () => c31__afyonkarahisar as unknown as DoctorSummary[]],
  ["adiyaman", () => c32__adiyaman as unknown as DoctorSummary[]],
  ["duzce", () => c33__duzce as unknown as DoctorSummary[]],
  ["ordu", () => c34__ordu as unknown as DoctorSummary[]],
  ["bolu", () => c35__bolu as unknown as DoctorSummary[]],
  ["batman", () => c36__batman as unknown as DoctorSummary[]],
  ["giresun", () => c37__giresun as unknown as DoctorSummary[]],
  ["zonguldak", () => c38__zonguldak as unknown as DoctorSummary[]],
  ["sivas", () => c39__sivas as unknown as DoctorSummary[]],
  ["aksaray", () => c40__aksaray as unknown as DoctorSummary[]],
  ["amasya", () => c41__amasya as unknown as DoctorSummary[]],
  ["tokat", () => c42__tokat as unknown as DoctorSummary[]],
  ["mardin", () => c43__mardin as unknown as DoctorSummary[]],
  ["agri", () => c44__agri as unknown as DoctorSummary[]],
  ["kutahya", () => c45__kutahya as unknown as DoctorSummary[]],
  ["afyon", () => c46__afyon as unknown as DoctorSummary[]],
  ["osmaniye", () => c47__osmaniye as unknown as DoctorSummary[]],
  ["usak", () => c48__usak as unknown as DoctorSummary[]],
  ["burdur", () => c49__burdur as unknown as DoctorSummary[]],
  ["erzincan", () => c50__erzincan as unknown as DoctorSummary[]],
  ["bitlis", () => c51__bitlis as unknown as DoctorSummary[]],
  ["kirklareli", () => c52__kirklareli as unknown as DoctorSummary[]],
  ["kastamonu", () => c53__kastamonu as unknown as DoctorSummary[]],
  ["yalova", () => c54__yalova as unknown as DoctorSummary[]],
  ["rize", () => c55__rize as unknown as DoctorSummary[]],
  ["bartin", () => c56__bartin as unknown as DoctorSummary[]],
  ["yozgat", () => c57__yozgat as unknown as DoctorSummary[]],
  ["bilecik", () => c58__bilecik as unknown as DoctorSummary[]],
  ["sirnak", () => c59__sirnak as unknown as DoctorSummary[]],
  ["bingol", () => c60__bingol as unknown as DoctorSummary[]],
  ["kars", () => c61__kars as unknown as DoctorSummary[]],
  ["nigde", () => c62__nigde as unknown as DoctorSummary[]],
  ["artvin", () => c63__artvin as unknown as DoctorSummary[]],
  ["cankiri", () => c64__cankiri as unknown as DoctorSummary[]],
  ["hakkari", () => c65__hakkari as unknown as DoctorSummary[]],
  ["nevsehir", () => c66__nevsehir as unknown as DoctorSummary[]],
  ["kirikkale", () => c67__kirikkale as unknown as DoctorSummary[]],
  ["karabuk", () => c68__karabuk as unknown as DoctorSummary[]],
  ["karaman", () => c69__karaman as unknown as DoctorSummary[]],
  ["mus", () => c70__mus as unknown as DoctorSummary[]],
  ["igdir", () => c71__igdir as unknown as DoctorSummary[]],
  ["kirsehir", () => c72__kirsehir as unknown as DoctorSummary[]],
  ["siirt", () => c73__siirt as unknown as DoctorSummary[]],
  ["sinop", () => c74__sinop as unknown as DoctorSummary[]],
  ["gumushane", () => c75__gumushane as unknown as DoctorSummary[]],
  ["ardahan", () => c76__ardahan as unknown as DoctorSummary[]],
  ["bayburt", () => c77__bayburt as unknown as DoctorSummary[]],
  ["tunceli", () => c78__tunceli as unknown as DoctorSummary[]],
  ["kilis", () => c79__kilis as unknown as DoctorSummary[]],
  ["istanbul", new Map([
    ["acil-tip", () => c80__istanbul__acil_tip as unknown as DoctorSummary[]],
    ["aile-hekimligi", () => c81__istanbul__aile_hekimligi as unknown as DoctorSummary[]],
    ["anesteziyoloji-ve-reanimasyon", () => c82__istanbul__anesteziyoloji_ve_reanimasyon as unknown as DoctorSummary[]],
    ["beyin-ve-sinir-cerrahisi", () => c83__istanbul__beyin_ve_sinir_cerrahisi as unknown as DoctorSummary[]],
    ["cocuk-cerrahisi", () => c84__istanbul__cocuk_cerrahisi as unknown as DoctorSummary[]],
    ["cocuk-hastaliklari", () => c85__istanbul__cocuk_hastaliklari as unknown as DoctorSummary[]],
    ["dermatoloji", () => c86__istanbul__dermatoloji as unknown as DoctorSummary[]],
    ["dis-hekimligi", () => c87__istanbul__dis_hekimligi as unknown as DoctorSummary[]],
    ["diyetisyen", () => c88__istanbul__diyetisyen as unknown as DoctorSummary[]],
    ["endokrinoloji", () => c89__istanbul__endokrinoloji as unknown as DoctorSummary[]],
    ["enfeksiyon-hastaliklari", () => c90__istanbul__enfeksiyon_hastaliklari as unknown as DoctorSummary[]],
    ["estetik-cerrahi", () => c91__istanbul__estetik_cerrahi as unknown as DoctorSummary[]],
    ["fizik-tedavi", () => c92__istanbul__fizik_tedavi as unknown as DoctorSummary[]],
    ["gastroenteroloji", () => c93__istanbul__gastroenteroloji as unknown as DoctorSummary[]],
    ["genel-cerrahi", () => c94__istanbul__genel_cerrahi as unknown as DoctorSummary[]],
    ["gogus-cerrahisi", () => c95__istanbul__gogus_cerrahisi as unknown as DoctorSummary[]],
    ["gogus-hastaliklari", () => c96__istanbul__gogus_hastaliklari as unknown as DoctorSummary[]],
    ["goz-hastaliklari", () => c97__istanbul__goz_hastaliklari as unknown as DoctorSummary[]],
    ["hematoloji", () => c98__istanbul__hematoloji as unknown as DoctorSummary[]],
    ["ic-hastaliklari", () => c99__istanbul__ic_hastaliklari as unknown as DoctorSummary[]],
    ["kadin-hastaliklari-ve-dogum", () => c100__istanbul__kadin_hastaliklari_ve_dogum as unknown as DoctorSummary[]],
    ["kalp-ve-damar-cerrahisi", () => c101__istanbul__kalp_ve_damar_cerrahisi as unknown as DoctorSummary[]],
    ["kardiyoloji", () => c102__istanbul__kardiyoloji as unknown as DoctorSummary[]],
    ["kbb", () => c103__istanbul__kbb as unknown as DoctorSummary[]],
    ["medikal-onkoloji", () => c104__istanbul__medikal_onkoloji as unknown as DoctorSummary[]],
    ["nefroloji", () => c105__istanbul__nefroloji as unknown as DoctorSummary[]],
    ["noroloji", () => c106__istanbul__noroloji as unknown as DoctorSummary[]],
    ["ortodonti", () => c107__istanbul__ortodonti as unknown as DoctorSummary[]],
    ["ortopedi-ve-travmatoloji", () => c108__istanbul__ortopedi_ve_travmatoloji as unknown as DoctorSummary[]],
    ["psikiyatri", () => c109__istanbul__psikiyatri as unknown as DoctorSummary[]],
    ["psikoloji", () => c110__istanbul__psikoloji as unknown as DoctorSummary[]],
    ["radyasyon-onkolojisi", () => c111__istanbul__radyasyon_onkolojisi as unknown as DoctorSummary[]],
    ["radyoloji", () => c112__istanbul__radyoloji as unknown as DoctorSummary[]],
    ["romatoloji", () => c113__istanbul__romatoloji as unknown as DoctorSummary[]],
    ["uroloji", () => c114__istanbul__uroloji as unknown as DoctorSummary[]],
  ])],
  ["ankara", new Map([
    ["acil-tip", () => c115__ankara__acil_tip as unknown as DoctorSummary[]],
    ["aile-hekimligi", () => c116__ankara__aile_hekimligi as unknown as DoctorSummary[]],
    ["anesteziyoloji-ve-reanimasyon", () => c117__ankara__anesteziyoloji_ve_reanimasyon as unknown as DoctorSummary[]],
    ["beyin-ve-sinir-cerrahisi", () => c118__ankara__beyin_ve_sinir_cerrahisi as unknown as DoctorSummary[]],
    ["cocuk-cerrahisi", () => c119__ankara__cocuk_cerrahisi as unknown as DoctorSummary[]],
    ["cocuk-hastaliklari", () => c120__ankara__cocuk_hastaliklari as unknown as DoctorSummary[]],
    ["dermatoloji", () => c121__ankara__dermatoloji as unknown as DoctorSummary[]],
    ["dis-hekimligi", () => c122__ankara__dis_hekimligi as unknown as DoctorSummary[]],
    ["diyetisyen", () => c123__ankara__diyetisyen as unknown as DoctorSummary[]],
    ["endokrinoloji", () => c124__ankara__endokrinoloji as unknown as DoctorSummary[]],
    ["enfeksiyon-hastaliklari", () => c125__ankara__enfeksiyon_hastaliklari as unknown as DoctorSummary[]],
    ["estetik-cerrahi", () => c126__ankara__estetik_cerrahi as unknown as DoctorSummary[]],
    ["fizik-tedavi", () => c127__ankara__fizik_tedavi as unknown as DoctorSummary[]],
    ["gastroenteroloji", () => c128__ankara__gastroenteroloji as unknown as DoctorSummary[]],
    ["genel-cerrahi", () => c129__ankara__genel_cerrahi as unknown as DoctorSummary[]],
    ["gogus-cerrahisi", () => c130__ankara__gogus_cerrahisi as unknown as DoctorSummary[]],
    ["gogus-hastaliklari", () => c131__ankara__gogus_hastaliklari as unknown as DoctorSummary[]],
    ["goz-hastaliklari", () => c132__ankara__goz_hastaliklari as unknown as DoctorSummary[]],
    ["hematoloji", () => c133__ankara__hematoloji as unknown as DoctorSummary[]],
    ["ic-hastaliklari", () => c134__ankara__ic_hastaliklari as unknown as DoctorSummary[]],
    ["kadin-hastaliklari-ve-dogum", () => c135__ankara__kadin_hastaliklari_ve_dogum as unknown as DoctorSummary[]],
    ["kalp-ve-damar-cerrahisi", () => c136__ankara__kalp_ve_damar_cerrahisi as unknown as DoctorSummary[]],
    ["kardiyoloji", () => c137__ankara__kardiyoloji as unknown as DoctorSummary[]],
    ["kbb", () => c138__ankara__kbb as unknown as DoctorSummary[]],
    ["medikal-onkoloji", () => c139__ankara__medikal_onkoloji as unknown as DoctorSummary[]],
    ["nefroloji", () => c140__ankara__nefroloji as unknown as DoctorSummary[]],
    ["noroloji", () => c141__ankara__noroloji as unknown as DoctorSummary[]],
    ["ortodonti", () => c142__ankara__ortodonti as unknown as DoctorSummary[]],
    ["ortopedi-ve-travmatoloji", () => c143__ankara__ortopedi_ve_travmatoloji as unknown as DoctorSummary[]],
    ["psikiyatri", () => c144__ankara__psikiyatri as unknown as DoctorSummary[]],
    ["psikoloji", () => c145__ankara__psikoloji as unknown as DoctorSummary[]],
    ["radyasyon-onkolojisi", () => c146__ankara__radyasyon_onkolojisi as unknown as DoctorSummary[]],
    ["radyoloji", () => c147__ankara__radyoloji as unknown as DoctorSummary[]],
    ["romatoloji", () => c148__ankara__romatoloji as unknown as DoctorSummary[]],
    ["uroloji", () => c149__ankara__uroloji as unknown as DoctorSummary[]],
  ])],
]);

// Lazy loaded indeksler
let _bySlug: Map<string, DoctorSummary> | null = null;
let _allCount: number | null = null;

function isLoaderFn(v: CityLoader): v is () => DoctorSummary[] {
  return typeof v === "function";
}

function loadCityAll(city: string): DoctorSummary[] {
  const v = CITY_REGISTRY.get(city);
  if (!v) return [];
  if (isLoaderFn(v)) return v();
  // big city: tüm alt shard'ları birleştir + dedupe (aynı doktor birden çok branşta görünebilir)
  const out: DoctorSummary[] = [];
  const seen = new Set<string>();
  for (const loader of v.values()) {
    for (const d of loader()) {
      if (seen.has(d.slug)) continue;
      seen.add(d.slug);
      out.push(d);
    }
  }
  return out;
}

export function findDtDoctor(slug: string): DoctorSummary | undefined {
  if (!_bySlug) {
    _bySlug = new Map();
    for (const city of CITY_REGISTRY.keys()) {
      for (const d of loadCityAll(city)) _bySlug.set(d.slug, d);
    }
  }
  return _bySlug.get(slug);
}

export function dtDoctorsByCity(citySlug: string): DoctorSummary[] {
  return loadCityAll(citySlug);
}

export function dtDoctorsBySpecialty(specialtySlug: string): DoctorSummary[] {
  // Tüm şehirleri tarar (yavaş ama az kullanılan path); branş hub'larında
  const out: DoctorSummary[] = [];
  for (const [city, v] of CITY_REGISTRY.entries()) {
    if (isLoaderFn(v)) {
      for (const d of v()) {
        if (d.specialtySlugs.includes(specialtySlug)) out.push(d);
      }
    } else {
      const sub = v.get(specialtySlug);
      if (sub) out.push(...sub());
    }
    void city;
  }
  return out;
}

export function dtDoctorsByCityAndSpecialty(
  citySlug: string,
  specialtySlug: string,
): DoctorSummary[] {
  const v = CITY_REGISTRY.get(citySlug);
  if (!v) return [];
  if (isLoaderFn(v)) {
    return v().filter((d) => d.specialtySlugs.includes(specialtySlug));
  }
  const sub = v.get(specialtySlug);
  return sub ? sub() : [];
}

export function allDtDoctorSlugs(): string[] {
  if (_bySlug) return [..._bySlug.keys()];
  // İlk çağrıda findDtDoctor'u herhangi bir slug ile çağırırsak _bySlug dolar
  // ama burada findDtDoctor'u dummy slug ile çağırmak yerine direkt build:
  _bySlug = new Map();
  for (const city of CITY_REGISTRY.keys()) {
    for (const d of loadCityAll(city)) _bySlug.set(d.slug, d);
  }
  return [..._bySlug.keys()];
}

export function dtDoctorCount(): number {
  if (_allCount !== null) return _allCount;
  let n = 0;
  for (const city of CITY_REGISTRY.keys()) n += loadCityAll(city).length;
  _allCount = n;
  return n;
}
